### ISSUE TITLE
Arrow triangle thing scrolls on category page

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#1]
The white bit stays in place when I scroll.
![screen shot 2014-08-18 at 2 10 55 pm](https://cloud.githubusercontent.com/assets/81672/3958099/2d3654f6-271c-11e4-93f3-b1aee121f7c8.png)

**Comment by zol** [comment]
Seems to be some sort of browser artifact under chrome, not seeing it in the sim.

**Comment by domyen** [comment]
I can't seem to reproduce this in Mac Chrome 36 or latest Safari.

**Comment by zol** [comment]
Strange, I'm on chrome Version 36.0.1985.143 (latest). Not seeing it in
Safari either.

On Mon, Aug 18, 2014 at 3:37 PM, Dominic Nguyen notifications@github.com
wrote:

> I can't seem to reproduce this in Mac Chrome 36 or latest Safari.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/percolatestudio/mdg-recipes/issues/1#issuecomment-52565429
> .

## 

_Zoltan Olah_
Partner/Engineer
http://percolatestudio.com
+1 415 696 4455

**Comment by zol** [comment]
No longer seeing this on my new MBP with (presumably) a newer version of chrome. Going to write it off as a glitch, closing.
