### ISSUE TITLE
Missing images on frontpage

### ISSUE THREAD

**Issue by Slava** [percolatestudio/mdg-localmarket#11]
It doesn't happen in the emulator but happens on the device. @arbesfeld thoughts?

**Comment by Slava** [comment]
On my device, if I go to recipes, pictures of seasons show up (like "spring bites", "summer tastes", etc), even though they have absolute urls as CSS 'background-image': `url('/img/app/bg-seasons-summer-640x240.jpg')`

**Comment by arbesfeld** [comment]
We may be translating these to relative as part of the CSS compilation step.

**Comment by Slava** [comment]
Yeah, the CSS explanation makes sense.

I noticed that images work after first HCP. Maybe it has something to do with loading a page from bundle vs loading it from disk.

**Comment by Slava** [comment]
I have a suspicion, it has something to do with IronRouter rewriting paths. `window.location.href` is '/' on front-page.

**Comment by zol** [comment]
@Slava - Are you actively looking into this bug (on the cordova branch) or should we pick it up and look at it?

**Comment by Slava** [comment]
@zol I spent a lot of time and now I think it is the fault of iron-router. Once Iron-Router supports hash fragments, I will continue looking into it.

But! I can be just confused on how browsers work and I missed something crucial so feel free to look at it as well.

**Comment by zol** [comment]
@Slava thanks! cc/ @tmeasday

**Comment by tmeasday** [comment]
@Slava TBH I'm confused about how images are supposed to / going to work with Cordova. 

If I specify images **without** a leading `/`, then they break when I route around the app outside of cordova (in the regular browser).

If I specify them **with** a leading `/`, they break in Cordova.

Is there a solution that works in both cases? Or do we need to check `Meteor.isCordova` all over the place when putting down images?

**Comment by tmeasday** [comment]
@Slava also I spoke to Chris and he'll get a pre-release of IR 0.10.0 (with built-in hash frag support) out either tomorrow or Monday.

**Comment by Slava** [comment]
@tmeasday looking at this again, you are right - image paths are probably different on Cordova and on Browser. We don't have a good story for that right now, one of the solutions could be using a special Blaze helper like `{{absolutePathPrefix}}`, and in the browser it is always '/', for Cordova it is something like `file:///Applications/uid/appname.app/www/` or something else on Android.

Yeah, I chatted with Chris too and he also promised to release a new closer to monday. I also scheduled some pairing with him tomorrow.

**Comment by tmeasday** [comment]
@Slava heh, no worries. I think we are having a triangular conversation with Chris. Anyway, I think I briefed him on my concerns so we'll see what you guys come up with.

On the image path issue, do let us know what answer you want us to use in this app (or make the change yourself) :).

**Comment by zol** [comment]
Goddamn ios. I've noticed sometimes `document.baseURI` is like`file:///recipes/Doxuwodzeh2G6anAh` (seen when running on a real device and the simulator) and sometimes it's like `file:///Users/zol/Library/Application%20Support/iPhone%20Simulator/7.1/Applications/2F65AB11-E132-43F0-9860-B10BDA689174/Documents/meteor/69fd5de33cacce0c3a3d50e7c6522fcd17d6ea83/` (only seen on the simulator).

@Slava @tmeasday - have you guys noticed this before? Any idea why it might be different in different cases and why in the second case (absolute path to /Users/zol...) it doesn't include the path to the current route (recipes/Doxuwodzeh2G6anAh).

**Comment by Slava** [comment]
@zol I don't have a 100% correct and expanded answer but I would rather not rely on `document.baseURI` on Cordova. First of all emulator and the device are not identical environments (and they don't even try to make it identical). Secondly, depending on if you hot-code pushed or not, the path can be different. 

We are working on making it consistent and easier, but cannot guarantee that it will become better at least until next release.

**Comment by zol** [comment]
@Slava - yeah, I've now realized that. What is the approach you're working on? Should we stop bothering to try and fix this issue till you've finalized the approach? Currently there doesn't seem to be a relative path option that is consistent across all Meteor-Cordova environments.

**Comment by stubailo** [comment]
Yeah, we are working on a new way to fix the URL problem right now, if it works then everything should be a lot better. We'll know by tomorrow probably.

**Comment by zol** [comment]
@Slava , @stubailo have you guys been able to test Sous with the latest RC? AFAIK Chris hasn't made a compatible release of iron:router yet, did you guys hack one together for testing?

**Comment by Slava** [comment]
I am on vacation since today. So I didn't have a chance to port Sous to 0.9.2-rc8. Starting from 0.9.2-rc5 we have a different serving approach and hopefully now all the web-app code should work on mobile as is (no code changes, no relative paths, no special iron:router).

**Comment by zol** [comment]
Thanks, yeah I'm hoping it just works out of the box but having trouble
with iron:router and the constraint solver. Enjoy your vacation!

_Zoltan Olah_
Partner/Engineer
http://percolatestudio.com
+1 415 696 4455

**Comment by zol** [comment]
Fixed by `0.9.2`
