### ISSUE TITLE
Rename files

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#12]
Out of today's conversation:

(just notes for myself)
- [x] recipes.json
- [x] main*
- [x] body -> appBody
- [x] /lib/collections/recipes.js ->  /lib/recipes.js
- [x] publishCounts -> Counts.publish

**Comment by zol** [comment]
@tmeasday could you please update/fix publishCounts and rename it's use here. `0.3.0` isn't working and I'm not setup as a maintainer for it.

**Comment by tmeasday** [comment]
Done. Added you as a maintainer if you need to publish a new version on a different Meteor 0.9.2 RC (0.9.2-rc branch).
