### ISSUE TITLE
Move momentum plugins into the project

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#13]
A decision made in today's meeting was to move momentum plugins directly into the project and attach via the `rendered` callback.

Also, we won't worry about loading templates when transitioning routes.

**Comment by tmeasday** [comment]
We also use momentum to fade in the email overlay.

Shall we use `uihooks` for this or just use CSS after all? @dominicnguyen ?

**Comment by domyen** [comment]
@tmeasday uihooks is a better pattern for overlays IMO

**Comment by domyen** [comment]
lgtm
