### ISSUE TITLE
Remove XXXs

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#14]
When IR + Cordova are ready.

**Comment by tmeasday** [comment]
The main one I'm looking to remove is the back button hackery. 

An unreleased branch of Iron Location gives us the tools we need for this, but there's still a lot of code to keep track of pages in history and use them to tell if a popState is a "back": https://github.com/EventedMind/iron-location/blob/historyState/examples/backTracker/backTracker.js#L2-L46

We also probably want to put some code to stop the back button taking us off site, which isn't entirely unavoidable.

I think there are some things to discuss here.

**Comment by tmeasday** [comment]
@zol - what do you think about this: https://github.com/percolatestudio/mdg-recipes/blob/1e2ea6850271fbfce8faafe9c417cb6570d4add8/client/templates/app-body.js#L37-L66

I figured out a way to remove the autorun and I think the end result is pretty simple and easy to understand. 

PS you need the `historyState` branch of iron:location to run this right now. Am trying to get it merged. (cc @cmather ;) )

**Comment by zol** [comment]
It looks good to me. Are we being inconsistent by having a setter but not a
getter (and not doing the same for `goingBack`)? If `initiator` and
`goingBack` are private to this file perhaps we should declare them at the
top and just use them directly?​

**Comment by zol** [comment]
I'm going to close this off for the moment as it looks like we're going to release with the IR related XXX's before we move to IR 1.0.
