### ISSUE TITLE
Brief 404 when transitioning over to a recipe page

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#19]
Perhaps we don't worry about this as we're moving to storing recipes in memory on the client.

**Comment by tmeasday** [comment]
If not we need to figure out if we are doing in-page loading or not.

**Comment by tmeasday** [comment]
Going to disable the recipe 404 for now until we figure it out.

**Comment by tmeasday** [comment]
Ok, there's no need to worry, no need to wait given local data.

**Comment by zol** [comment]
Yep, looks good!
