### ISSUE TITLE
Transitioner needs to preserve scroll position when moving back and forth

### ISSUE THREAD

**Issue by domyen** [percolatestudio/mdg-localmarket#2]
Repro:
1. Scroll to the midway down the home screen
2. Tap recipe
3. Tap back button

**Comment by tmeasday** [comment]
Ahh. This is a IR plugin that I've wanted to write for a while. Will do a first version.

**Comment by tmeasday** [comment]
Gave it a try and ran into some issues. Will discuss with Chris a solution.

I wouldn't suggest waiting for a fix here is a good idea. Move forward without it.

**Comment by tmeasday** [comment]
Added some code to the ir-1.0 branch (you need an unreleased version of IR for it to work) that does it. Here https://github.com/percolatestudio/mdg-recipes/blob/ir-1.0/client/templates/app-body.js#L8-L34

Kind of arcane. Ideally it should be a package that abstracts it away I would have thought.

**Comment by zol** [comment]
Closing this for the time being as the 0.9 IR solution is very ugly. Re-open when IR 1.0 comes out and we switch to it. Plenty of real world (including native) apps don't maintain scroll position.
