### ISSUE TITLE
Janky transition when scrolling activity items into view

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#21]

**Comment by zol** [comment]
@tmeasday I've tried monkeying around with `getBoundingClientRect` to try to calculate what to `scrollTo` without much luck (maybe I'm not calculating the right value at the right time). Interestingly, the `.scrollIntoView()` works (in that it scrolls to the right position). When I have it in a `setTimeout` of `100`, so a number that's less than the LR transition time but greater than some smallish value it works as we want it.

Obviously, I don't want to have a magic constant in a setTimeout so I'd love to actually work out what's going on here.

**Comment by tmeasday** [comment]
The issue was that it was scrolling sideways somehow (you can see it if you slow the animation way down).

I implemented a simple fix that just calculates the scroll-top. 

A alternate solution would be to avoid the side-ways scrolling. Not sure if that's feasible.

**Comment by zol** [comment]
Nice work T, they call him the scrollmeister...
