### ISSUE TITLE
Move feed into it's own "what's cooking" section

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#23]
Matt: Seeing this in action, I want to move the feed into a separate page
called "What's Cooking".  Accessed from a new sidebar menu option
called "What's Cooking" in the second position of the nav.

**Comment by domyen** [comment]
Added the menu placeholder. Feel free to link it to the new route.

**Comment by tmeasday** [comment]
Ok, hooked it up. Final styling.

Also, this page more than any other needs loading state.

**Comment by domyen** [comment]
Styled per https://github.com/percolatestudio/mdg-recipes/commit/236bdf3a6f9dd5b28ba48aeaed0e8d91cd77872f. @tmeasday or @zol do we have a loading template?

**Comment by zol** [comment]
@dominicnguyen added loading section on feed , over to you

**Comment by zol** [comment]
Looks great!
