### ISSUE TITLE
Unable to start the app

### ISSUE THREAD

**Issue by tmeasday** [percolatestudio/mdg-localmarket#3]
Strangely when I run the app, meteor hangs on "starting your app" and heaps of dead node processes start appearing. No logging anywhere.

@zol - any ideas? Do you see this locally?

I've tried recloning and everything.

**Comment by zol** [comment]
Nope, I don't see this. Try now (`master` is on 0.9)

**Comment by tmeasday** [comment]
Ok, just going to close this one. Was super weird though. I even tried reinstalling meteor.
