### ISSUE TITLE
Twitter text should match feed text

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#30]
Matt: Twitter text should match the feed text, plus the hashtag #localmarket.

Zol: We should truncate and ellipsize the share text at the right char limit and append #localmarket.

**Comment by tmeasday** [comment]
I think we already limit the share text to the right length?

**Comment by zol** [comment]
No we don't, see: https://github.com/percolatestudio/mdg-recipes/issues/42
