### ISSUE TITLE
Remove tweet text

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#32]
As it's now the same as the share feed text. Also change the checkbox to be checked by default and the label to 'Also post to twitter'.

**Comment by domyen** [comment]
Changed copy & first pass at removing these styles. https://github.com/percolatestudio/mdg-recipes/commit/289e7b54f5b325de95318fc2e2787ce076f1ab35

**Comment by zol** [comment]
Lgtm.
