### ISSUE TITLE
Extra copy next to phone chrome on desktop and an admin link

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#41]
We're going to include some copy next to the phone talking about how mdg + percolate made this example app and that you can just run it on your device with one command. In addition, we'll include a link to the 'backend admin' page which will allow the first authenticated twitter use to change the news item text.

**Comment by domyen** [comment]
Done. https://github.com/percolatestudio/mdg-recipes/commit/032934861d22a37a88d6214aed0958b27a3351b8

**Comment by zol** [comment]
Looks good, ty
