### ISSUE TITLE
Activity: Create new activity-item template to differentiate 'what's cooking' from recipe/pictures

### ISSUE THREAD

**Issue by domyen** [percolatestudio/mdg-localmarket#48]

**Comment by zol** [comment]
I'm closing this ticket as:
1. I don't think the activity item should look different as the whole point of scrolling it into view was to ensure that it gave the user context as they are teleported to the feed section of the activity page.
2. I'm not sure the added code complexity is worth it.

Let's re-open this ticket if we decide to revisit this.
