### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#5]
Clicking 'send recipe' throws js error.

**Comment by tmeasday** [comment]
Not seeing this? Is it fixed for you?

**Comment by zol** [comment]
Nope, still seeing it. I can take a look at why if you can't reproduce it:
![screen shot 2014-09-04 at 11 13 29 am](https://cloud.githubusercontent.com/assets/81672/4154148/41eb2aca-345f-11e4-8ada-3c84d4a1579c.png)

**Comment by tmeasday** [comment]
Right. Happened on a category page, but a recipe page was OK.
