### ISSUE TITLE
Console warnings/errors in safari

### ISSUE THREAD

**Issue by zol** [percolatestudio/mdg-localmarket#8]
@tmeasday @dominicnguyen do we care? It's bizarre that safari complains about the minimal-ui key as it's apple's own :-/

![screen shot 2014-09-02 at 1 58 14 pm](https://cloud.githubusercontent.com/assets/81672/4125693/26961108-32e4-11e4-81b3-0a0dd60784cf.png)

**Comment by domyen** [comment]
The CSS errors come from the reset.css and are used for IE. It's nbd for me. 
Re: minimal-ui, let's leave it.

**Comment by zol** [comment]
Closing.
